logLevel: debug

server:
  host: 0.0.0.0
  port: 8000
  timeout: 30s
  path: "/"

worker:
  interval: 10s

networks:
  - name: "ethereum-mainnet"
    url: "https://cloudflare-eth.com"
  - name: "bsc-mainnet"
    url: "https://bsc-dataseed.binance.org"
  - name: "polygon-mainnet"
    url: "https://polygon-rpc.com"
  - name: "arbitrum-mainnet"
    url: "https://arbitrum.llamarpc.com"
  - name: "fantom-mainnet"
    url: "https://rpc.fantom.network"

