logLevel: info

server:
  host: 0.0.0.0
  port: 8000
  timeout: 30s
  path: "/"

worker:
  interval: 10s

networks:
  - name: "ethereum-mainnet"
    url: "https://cloudflare-eth.com"
  - name: "bsc-mainnet"
    url: "https://bsc-dataseed.binance.org"
  - name: "polygon-mainnet"
    url: "https://polygon-rpc.com"
  - name: "fantom-opera-mainnet"
    url: "https://rpc.fantom.network"
  - name: "arbitrum-one-mainnet"
    url: "https://arbitrum.llamarpc.com"
  - name: "optimism-mainnet"
    url: "https://mainnet.optimism.io"
  - name: "avalanche-mainnet"
    url: "https://api.avax.network/ext/bc/C/rpc"
  - name: "cronos-mainnet"
    url: "https://evm.cronos.org"
  - name: "base-mainnet"
    url: "https://mainnet.base.org"
  - name: "gnosis-mainnet"
    url: "https://gnosis.publicnode.com"
